// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console} from "forge-std/Script.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {RegiFeeSplitter} from "../../src/buyback/RegiFeeSplitter.sol";
import {PoolKey, IPoolManagerMinimal, V4Lib} from "../../src/buyback/UniswapV4Minimal.sol";
import {INanoLedgerMinimal} from "../../src/buyback/INanoLedgerMinimal.sol";
import {RegiBuybackRehearsal} from "../../test/buyback/rehearsal/RegiBuybackRehearsal.sol";
import {RehearsalREGI, RehearsalLiquidity, IPoolManagerLiquidity} from "../../test/buyback/rehearsal/RehearsalPool.sol";

/// @notice ARC TESTNET ONLY. A rehearsal of the REGI buyback against the real Uniswap v4
///         PoolManager, real testnet USDC (Arc's native-transfer precompile) and the real
///         testnet NanoLedger: a stand-in token (tREGI), a pool deep in tREGI seeded at a
///         tick boundary (so no USDC is needed for liquidity), RegiBuybackRehearsal (the
///         real contract with a $2 trigger / $0.50 chunks / 1-minute cooldown, generated by
///         test/buyback/rehearsal/make-rehearsal.sh) and the real RegiFeeSplitter with SAFE = ME.
///
///   ME=0x… TICK_HI=… TICK_LO=… INIT_SQRT=… LIQ=… \
///     forge script script/testnet/BuybackRehearsal.s.sol --rpc-url arc_testnet --private-key … --broadcast
contract BuybackRehearsal is Script {
    address constant PM = 0x8366a39CC670B4001A1121B8F6A443A643e40951; // same address on Arc testnet
    address constant USDC = 0x3600000000000000000000000000000000000000;
    address constant LEDGER = 0x02D278930B67A290fEfE93Ac049a086A9b5e0FB5; // testnet NanoLedger (USDC 0x3600)

    function run() external {
        require(block.chainid == 5042002, "BuybackRehearsal: Arc testnet only");
        address me = vm.envAddress("ME");
        int24 hi = int24(vm.envInt("TICK_HI"));
        int24 lo = int24(vm.envInt("TICK_LO"));
        uint160 init = uint160(vm.envUint("INIT_SQRT"));
        int256 liq = vm.envInt("LIQ");

        vm.startBroadcast();
        RehearsalREGI t = new RehearsalREGI();
        require(address(t) > USDC, "tREGI sorts below USDC: rerun (a new nonce gives a new address)");
        PoolKey memory key = PoolKey(USDC, address(t), 10_000, 200, address(0));
        int24 tick = IPoolManagerLiquidity(PM).initialize(key, init);
        RehearsalLiquidity lp = new RehearsalLiquidity(IPoolManagerLiquidity(PM));
        t.mint(address(lp), 2e27);
        // No USDC here: the price starts just above the range, so the position is all tREGI (and
        // a local simulation can't run Arc's USDC precompile anyway).
        lp.add(key, lo, hi, liq);
        RegiBuybackRehearsal bb = new RegiBuybackRehearsal(
            IPoolManagerMinimal(PM), IERC20(USDC), address(t), address(0), 10_000, 200, INanoLedgerMinimal(LEDGER)
        );
        RegiFeeSplitter sp = new RegiFeeSplitter(INanoLedgerMinimal(LEDGER), IERC20(USDC), me, address(bb));
        vm.stopBroadcast();

        require(V4Lib.poolId(bb.key()) == V4Lib.poolId(key), "pool key");
        console.log("tREGI                ", address(t));
        console.log("pool tick            ", vm.toString(tick));
        console.log("RegiBuybackRehearsal ", address(bb));
        console.log("RegiFeeSplitter      ", address(sp));
    }
}
